// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Review.proto

package com.github.fabriciolfj.proto;

public interface ProductReviewResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.fabriciolfj.proto.ProductReviewResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string evaluation = 2;</code>
   * @return The evaluation.
   */
  java.lang.String getEvaluation();
  /**
   * <code>string evaluation = 2;</code>
   * @return The bytes for evaluation.
   */
  com.google.protobuf.ByteString
      getEvaluationBytes();
}
