// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Review.proto

package com.github.fabriciolfj.proto;

public interface ProductReviewResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.fabriciolfj.proto.ProductReviewResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 rate = 3;</code>
   * @return The rate.
   */
  int getRate();

  /**
   * <code>string date = 4;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 4;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
