apiVersion: v1
kind: ConfigMap
metadata:
  name: postgrescatalog-config
  labels:
    app: postgres
data:
  POSTGRES_DB: catalog
  POSTGRES_USER: user
  POSTGRESQL_SERVICE_HOST: postgrescatalog
---
apiVersion: v1
kind: Secret
metadata:
  name: postgrescatalog-secret
  labels:
    app: postgrescatalog
data:
  POSTGRES_PASSWORD: YWRtaW4xMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrescatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrescatalog
  template:
    metadata:
      labels:
        app: postgrescatalog
    spec:
      containers:
        - name: postgrescatalog
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgrescatalog-config
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgrescatalog-config
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgrescatalog-secret
---
apiVersion: v1
kind: Service
metadata:
  name: postgrescatalog
  labels:
    app: postgrescatalog
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres