apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  labels:
    app: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: review-service
          image: fabricio211/review-service
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/review"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 8080
              name: rest
            - containerPort: 5001
              name: grpc
          resources:
            limits:
              memory: 1000Mi
              cpu: "500m"
            requests:
              memory: 1000Mi
              cpu: "500m"
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 40
            timeoutSeconds: 2
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 40
            timeoutSeconds: 2
            failureThreshold: 30
            successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  type: ClusterIP
  selector:
    app: review-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 5001
    name: grpc
    targetPort: 5001
