grpc:
  server:
    port: 5001

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    password: root
    username: root
    hikari:
      maximum-pool-size: 40
      connection-timeout: 300
  flyway:
    locations:
      - db/migration
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

server:
  shutdown: graceful
  port: 9091
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, flyway, heapdump, info
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
